Implementation for SBOL2<-->SBOL3 converter
SynBioDex/SBOL-utilities pull request #222
Opened 2023-10-19 01:09 UTC by Yehuda-Binik

In the new converter, I completed the `visit_implementation` function for both the `SBOL3To2ConversionVisitor` and `SBOL2To3ConversionVisitor` classes. I also added two test cases to test my code using the SBOL3 [implementation.nt](https://github.com/SynBioDex/SBOLTestSuite/blob/master/SBOL3/entity/implementation/implementation.nt) file from the [SBOLTestSuite](https://github.com/SynBioDex/SBOLTestSuite/tree/master).

2023-10-19 13:56 UTC, jakebeal commented
@Yehuda-Binik : there are some files that shouldn't have been checked in that were checked in. Can you please remove the `.idea` and `sbol_utilities.egg-info` directories?  In general, `.idea` and `*.egg-info` should be in your `.gitignore` files.

2023-10-20 17:43 UTC, Yehuda-Binik commented
@jakebeal I removed the `.idea` and `sbol_utilities.egg-info` directories. I also updated my `.gitignore` Is it necessary to delete my `.gitignore` file from the pull request as well? Let me know if there is anything left I need to change.

2023-10-21 10:47 UTC, jakebeal commented
Thank you! Adding to .gitignore is fine and helpful. I will review the PR in detail now.

2023-10-25 23:55 UTC, jakebeal requested changes
There's some minor cleanup needed - the substance of the changes is all good, I just need you to remove the accidental check-ins and unnecessary space changes.

2023-10-25 23:55 UTC, jakebeal commented on sbol_utilities/sbol3_sbol2_conversion.py
> +        # raise NotImplementedError('Conversion of Implementation from SBOL2 to SBOL3 not yet implemented')
Delete this comment as unneeded.

2023-10-25 23:55 UTC, jakebeal commented on test/sbol3.nt
This file is out of place: it's in the test directory, not the test_files subdirectory. It looks like an accidental check-in?

2023-10-25 23:55 UTC, jakebeal commented on test/test_files/sbol3_genbank_conversion/ignoring_sbol_properties.nt.test
This file also appears to be an accidental check-in.

2023-10-25 23:55 UTC, jakebeal commented on test/test_sbol2_sbol3_direct.py
> -
Please avoid making un-needed changes in spacing: it increases the likelihood of conflicts.
There are several locations, here and below.

2023-10-25 23:55 UTC, jakebeal commented on test/test_sbol2_sbol3_direct.py
> +        """Test ability to convert a simple part from SBOL2 to SBOL3"""
Good catch!

2023-10-31 00:58 UTC, Yehuda-Binik commented
I removed the two accidentally checked-in files deleted 3 unnecessary comments (the unneeded `raise NotImplemented` comment as well as two comments I had written myself) and removed superfluous formatting changes.

2023-10-31 10:47 UTC, jakebeal approved these changes
Code looks good, and the two errors are, I believe, only from the secret-requiring tests that are not affected by this PR

2023-10-31 10:47 UTC, merged