added fix for conversion between SBOL2 and SBOL3
SynBioDex/SBOL-utilities pull request #90
Opened 2022-01-27 20:50 UTC by Akshat-Kumar-0610

Hi @jakebeal, tried to work on the issue #83,

1. In the function convert3to2 I have removed the part where orientation were mapped again after conversion to SBOL2 document.
2. For the test for validation of orientation I have compaired orientation string to 'http://sbols.org/v3#inline' and if it  matches to the string test fails since it must not be present in an SBOL2 document.

2022-01-27 21:48 UTC, jakebeal requested changes

2022-01-27 21:48 UTC, jakebeal commented on test/test_conversion.py
> +                    assert loc.orientation != 'http://sbols.org/v3#inline'
Can we also have a positive check that we _do_ have some SBOL2 inline marks where expected? Orientation is optional, and so we need to make sure we're actually exercising the test - I don't know if the test file has an orientation in it at all.

2022-01-27 21:48 UTC, jakebeal commented
This is looking good; I'd like to see a strengthening of the test case, since I'm not sure if the test file has an orientation listed at all.

2022-01-28 13:58 UTC, Akshat-Kumar-0610 commented
Hi @jakebeal, I have made few changes:
1. I have shifted conversion of orientation to traverse method for recursive traversal of objects.
2. for the tests part I have tried to compare identity of location block if it has orientation attribute before and after conversion.
3. for the actual testing test_files/BBa_J23101.nt file which is being used in test_3to2_conversion function does not contain location block with orientaion. For testing the changes I used test_files/iGEM_SBOL2_imports.nt file through python's interactive shell.

2022-01-28 18:59 UTC, jakebeal requested changes
Thank you, nice progress. Just a couple of small tweaks to request in the code. 

With regards to this:
> for the actual testing test_files/BBa_J23101.nt file which is being used in test_3to2_conversion function does not contain location block with orientation. For testing the changes I used test_files/iGEM_SBOL2_imports.nt file through python's interactive shell.

I'm glad that it worked for your local test. We won't know if it's still working once somebody else changes the code, however, unless we add a test to the test suite. Can you add a new test that uses `test_files/iGEM_SBOL2_imports.nt`? Tests are cheap and bugs are expensive!

2022-01-28 18:59 UTC, jakebeal commented on test/test_conversion.py
> +        def change_if_location(o):
This isn't actually changing locations: its name should describe what it actually does.

2022-01-28 18:59 UTC, jakebeal commented on test/test_conversion.py
> +        doc3.traverse(change_if_location)
How many should there be? Add a check to see the number.

2022-01-29 05:09 UTC, Akshat-Kumar-0610 commented
Should I rewrite whole `test_3to2_conversion` function to use `test_files/iGEM_SBOL2_imports.nt` file or add another function just to test conversion of orientation?

2022-01-29 12:42 UTC, jakebeal commented
I would suggest adding another function to test conversion of orientation. The reason I suggest that is that one often gets better coverage and simpler debugging when there are a larger number of more focused tests, rather than a smaller number of more complex tests.

2022-01-29 20:17 UTC, Akshat-Kumar-0610 commented
Hi @jakebeal  I have added separate test to validate orientation conversion using file `test_files/iGEM_SBOL2_imports.nt` and all 11 tests are passing as of now.

2022-01-29 21:37 UTC, jakebeal approved these changes

2022-01-29 21:37 UTC, merged

2022-01-29 21:37 UTC, jakebeal commented
Looks good --- nice work and thank you!